import cv2
import numpy as np
import os
import sys
import glob
from keras.models import load_model

# Add the project root to sys.path so we can import 'segmentation'
# This points to D:\COS30018-HNRS-OptionB
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
if project_root not in sys.path:
    sys.path.append(project_root)

# Now import using the folder structure from the root
from src.segmentation.segmentation import process_image

# 1. Configuration
MODEL_PATH = 'src/model/bestmodel.keras'
INPUT_IMAGE_PATH = 'src/segmentation/input_image/test2.jpg'
OUTPUT_FOLDER = 'src/segmentation/output_digit'

# 2. Load Model
if not os.path.exists(MODEL_PATH):
    print(f"Error: Model file not found at {MODEL_PATH}")
    exit()

model = load_model(MODEL_PATH)

def run_pipeline(image_path):
    # Step 1: Use the official process_image from segmentation.py
    # This cleans the folder, segments the image, and saves digits
    print(f"--- Processing: {image_path} ---")
    process_image(image_path) 
    
    # Step 2: Predict using the files generated by process_image
    image_files = glob.glob(os.path.join(OUTPUT_FOLDER, "*.png"))
    
    if not image_files:
        print("No digits found in output folder.")
        return

    print("-" * 55)
    print(f"{'Filename':<20} | {'Digit':<10} | {'Confidence'}")
    print("-" * 55)

    for file_path in sorted(image_files):
        # Read image saved by segmentation (already 28x28 and binary)
        img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
        
        if img is not None:
            # Final normalization for the MNIST model
            img_input = img.astype('float32') / 255.0
            img_input = np.expand_dims(img_input, axis=(0, -1)) 
            
            # Prediction
            preds = model.predict(img_input, verbose=0)
            digit = np.argmax(preds)
            confidence = np.max(preds) * 100
            
            filename = os.path.basename(file_path)
            print(f"{filename:<20} | {digit:<10} | {confidence:>8.2f}%")

if __name__ == "__main__":
    run_pipeline(INPUT_IMAGE_PATH)